easy_admin:
    site_name: 'Foundations Fleets'
    entities:
        Fleet:
            class: App\Entity\Fleet
        FleetShip:
            class: App\Entity\FleetShip
        Player:
            class: App\Entity\Player
            form:
                fields:
                    - pseudo
                    - email
        Race:
            class: App\Entity\Race
        Ship:
            class: App\Entity\Ship
        ShipCategory:
            class: App\Entity\ShipCategory
    list:
        actions:
            - {name: show, icon: 'eye', label: false}
            - {name: edit, icon: 'pencil', label: false}
            - {name: delete, icon: 'trash', label: false}